@startuml

actor Usuario
participant UnObjeto
participant OtroObjeto

Usuario -> UnObjeto : pedirAlgo()
UnObjeto -> OtroObjeto : calcular(dato)
OtroObjeto --> UnObjeto : resultado
UnObjeto --> Usuario : respuesta

@enduml
